language: python
python:
  - 3.7
  - 3.8
# before executing tests
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - pytest --cov=./lib
# execute code coverage
after_success:
  - codecov